### ISSUE TITLE
[Docs] Files field query

### ISSUE THREAD

**Issue by tobiasfabian** [k-next/getkirby.com#152]
https://nnnnext.getkirby.com/docs/reference/fields/files

As far as i know there is no more `parent` option but a `query` option for the files field.

```yaml
gallery:
  type: files
  parent: site.find('imagefolder')
```

-->

```yaml
gallery:
  type: files
  query: site.find('imagefolder').files
```
