### ISSUE TITLE
[UI] Fix / remove margin-bottom on '.text pre'

### ISSUE THREAD

**Issue by sylvainjule** [k-next/getkirby.com#67]
```css
.text pre {
    margin-bottom: 1.5rem;
}
```
Shows this when x is overflowing:

<img width="657" alt="capture d ecran 2018-10-25 a 09 27 53" src="https://user-images.githubusercontent.com/14079751/47483066-9be45200-d838-11e8-8f7d-238944513f9f.png">
