### ISSUE TITLE
[Docs] Add `image:` Options to Files Section

### ISSUE THREAD

**Issue by luxlogica** [k-next/getkirby.com#77]
In the [Sections Page](https://nnnnext.getkirby.com/docs/guide/blueprints/sections), there is no documentation for the `image:` sub-options (`cover:`, `ratio:` and `back:`) that we *can* use in the Files Section - similar to the same sub-options for `image:` in the Pages Section, except that we don't have to specify `src:`. Example:

```
sections:
  images:
    headline: Page Images 
    type: files 
    layout: cards 
    template: image
    image:
      cover: true
      ratio: 1/1
      back: white
```
