### ISSUE TITLE
Is information about pages blueprint preset correct?

### ISSUE THREAD

**Issue by paulrobertlloyd** [k-next/getkirby.com#93]
On the page detailing blueprint presets, it suggests that for the pages preset, you can show unlisted pages, like follows:

```
title: Blog
preset: pages

unlisted:
  extends: sections/articles
  headline: Articles in review
```

However, when I use this code, I get the following error in the panel: `The blueprint "sections/articles" could not be loaded`. Is the documentation incorrect, or missing something? I suspect this documentation assumes you have set up a custom section, as [documented on another page of the docs](https://nnnnext.getkirby.com/docs/guide/blueprints/sections), but I can't be sure.
